spring.application.name=Shopping_Cart

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PWD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#server.servlet.context-path=/api/v1.0

spring.mail.host=smtp.gmail.com
spring.mail.username=kushwahasugam66@gmail.com
spring.mail.password=ockxpseruhwdcvup
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# spring.application.name=Shopping_Cart


