spring.application.name=Shopping_Cart

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/ecom_db
spring.datasource.username=root
spring.datasource.password=2006

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

#server.servlet.context-path=/api/v1.0

spring.mail.host=smtp.gmail.com
spring.mail.username=kushwahasugam66@gmail.com
spring.mail.password=ockxpseruhwdcvup
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# spring.application.name=Shopping_Cart

# # Dynamic port
# server.port=${PORT:8080}

# # Database (example: PostgreSQL from Render)
# spring.datasource.url=${SPRING_DATASOURCE_URL}
# spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
# spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.hibernate.ddl-auto=update

# # Mail settings (hidden via environment variables)
# spring.mail.host=smtp.gmail.com
# spring.mail.username=${MAIL_USERNAME}
# spring.mail.password=${MAIL_PASSWORD}
# spring.mail.port=587
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true

# # File upload
# spring.servlet.multipart.max-file-size=50MB
# spring.servlet.multipart.max-request-size=50MB
